#!/bin/sh



scriptdir=`pwd`
export scriptdir

export fctype=pollen

export COSMO_PATH=${scriptdir}/COSMO-meteo
export ICON_PATH=${scriptdir}/ICON-d2-meteo
export METEO_DIR=${ICON_PATH}
#export silam_binary=${scriptdir}/silam-model/bin/silam_v5_6.gnumpi # MPI run
export silam_binary=${scriptdir}/../silam-model/bin/silam_v5_8pub.gnu    # serial run
#export silam_binary=/home/kouzne/SILAM/silamgit/bin/silam_v5_7.gnu

#export boundary_path="/media/yury/c9152749-9c88-4b8c-8bf9-a2c17c62f585/Boundary conditions, SILAM, strt01.10.19"
#export boundary_path="/media/disk-6T/BoundariesFMI"
#export OMP_NUM_THREADS=8
if [ -n "${ECF_NAME}" ]; then 
  echo "Running form ecflow"
  export progresscmd="ecflow_client --meter=progress"
  #export MAILTO="rostislav.kouznetsov@fmi.fi,mikhail.sofiev@fmi.fi"
  export MAILTO="rostislav.kouznetsov@fmi.fi,Evgeny.Kadantsev@fmi.fi"

else
  echo "Running standalone: no mail!"
  export progresscmd="echo NON_OPER_PROGRESS"
  export MAILTO=""
fi

#export ny=1 ## Number of MPI tasks
export OUTPUTDIR=${scriptdir}/output

export outsuff="" ## Can be set non-empty to alter the  output directory

export fcdate=`date -u -d "3 hours" +%Y%m%d`

export fchour=00
export maxhours=48
#export fcdate=`date -u -d "-2 days" +%Y%m%d`


export PUTLOGOCMDPOLLEN="composite  -geometry  +70+515  $scriptdir/grads/fmi-logo-60x30a.png"
##export PUTLOGOCMDPOLLEN="composite  -geometry  +70+360  $scriptdir/../common/fmi-logo-60x30a.png"
#export PUTLOGOCMDPOLLEN="composite  -geometry  +40+460  $scriptdir/../common/FMI_EAN_logo_vert.png"
# Special logo for aqi and pollen index pictures
#export PUTLOGOCMDINDEX="composite  -geometry  +40+460  $scriptdir/grads/FMI-Health2.png"

# These guys prevent ecflow from trapping errors!
#set +u
#set +e
#set +x
